### PR TITLE
New Styles

### PR DESCRIPTION
**Pull request by creativejuiz**

### CODE REVIEW

**Comment by Screenfeed** [comment]
@creativejuiz We'll need this:

    .imgt-log-content-message.imgt-log-content-message code {
        background: none;
        color: #fff;
    }

**Comment by creativejuiz** [comment]
@Screenfeed Thank you. Done.

**Comment by Screenfeed** [comment]
Don't forget to assign me as reviewer when you are done, so I know the branch can be merged ;)

**Comment by creativejuiz** [comment]
@Screenfeed Ok sorry I forgot that.

**Comment by Screenfeed** [comment]
@creativejuiz Great job by the way :)

**Pull request merged**
